name: newsflash
base: core18
adopt-info: newsflash

grade: devel
confinement: devmode

slots:
  newsflash:
    interface: dbus
    bus: session
    name: com.gitlab.newsflash

apps:
  newsflash:
    command: com.gitlab.newsflash
    extensions:
      - gnome-3-34
    common-id: com.gitlab.newsflash
    desktop: usr/local/share/applications/com.gitlab.newsflash
    plugs:
      - audio-playback
      - network

parts:
  newsflash:
    plugin: meson
    source: https://gitlab.com/news-flash/news_flash_gtk.git
    source-tag: "1.0.5"
    parse-info: [usr/local/share/metainfo/com.gitlab.newsflash.appdata.xml]
    build-packages:
      - cargo
      - rustc
      - libgtk-3-dev
      - libssl-dev
    override-build: |
      snapcraftctl build

      sed -i 's|Icon=.*|Icon=${SNAP}/usr/local/share/icons/hicolor/scalable/apps/com.gitlab.newsflash.svg|g' \
        $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/com.gitlab.newsflash.desktop
